[package]
name = "light_phylogeny"
version = "0.1.0"
authors = ["Simon Penel <simon.penel@univ-lyon1.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
